apiVersion: apps/v1 
kind: Deployment
metadata:
  name: demo-api
spec: 
  selector:
    matchLabels:
      app: demo-api
  replicas: 1 # tells deployment to run 1 pod matching the template
  template:
    metadata:
      labels:
        app: demo-api
    spec:
      containers:
      - name: demo-api
        image: gcr.io/roidtc-march701/internal-image@sha256:0f3065cbdea1a4c2114c24b1c9c4db3271fa48b3bd4946497ffa0ee1228b655f
        ports:
        - containerPort: 8082
            
        
